const FLAGS: Record<string, string> = {
  // AFC (9)
  'australia': 'au', 'ออสเตรเลีย': 'au',
  'iran': 'ir', 'อิหร่าน': 'ir',
  'iraq': 'iq', 'อิรัก': 'iq',
  'japan': 'jp', 'ญี่ปุ่น': 'jp',
  'jordan': 'jo', 'จอร์แดน': 'jo',
  'korea republic': 'kr', 'south korea': 'kr', 'เกาหลีใต้': 'kr',
  'qatar': 'qa', 'กาตาร์': 'qa',
  'saudi arabia': 'sa', 'ซาอุดีอาระเบีย': 'sa',
  'uzbekistan': 'uz', 'อุซเบกิสถาน': 'uz',
  // CAF (10)
  'algeria': 'dz', 'แอลจีเรีย': 'dz',
  'cape verde': 'cv', 'เคปเวิร์ด': 'cv',
  "cote d'ivoire": 'ci', 'ivory coast': 'ci', 'côte d\'ivoire': 'ci', 'โกตดิวัวร์': 'ci',
  'dr congo': 'cd', 'democratic republic of congo': 'cd', 'สาธารณรัฐประชาธิปไตยคองโก': 'cd',
  'egypt': 'eg', 'อียิปต์': 'eg',
  'ghana': 'gh', 'กานา': 'gh',
  'morocco': 'ma', 'โมร็อกโก': 'ma',
  'senegal': 'sn', 'เซเนกัล': 'sn',
  'south africa': 'za', 'แอฟริกาใต้': 'za',
  'tunisia': 'tn', 'ตูนิเซีย': 'tn',
  // CONCACAF (6)
  'canada': 'ca', 'แคนาดา': 'ca',
  'curacao': 'cw', 'curaçao': 'cw', 'กูราเซา': 'cw',
  'haiti': 'ht', 'เฮติ': 'ht',
  'mexico': 'mx', 'เม็กซิโก': 'mx',
  'panama': 'pa', 'ปานามา': 'pa',
  'usa': 'us', 'united states': 'us', 'สหรัฐอเมริกา': 'us',
  // CONMEBOL (6)
  'argentina': 'ar', 'อาร์เจนตินา': 'ar',
  'brazil': 'br', 'brasil': 'br', 'บราซิล': 'br',
  'colombia': 'co', 'โคลอมเบีย': 'co',
  'ecuador': 'ec', 'เอกวาดอร์': 'ec',
  'paraguay': 'py', 'ปารากวัย': 'py',
  'uruguay': 'uy', 'อุรุกวัย': 'uy',
  // OFC (1)
  'new zealand': 'nz', 'นิวซีแลนด์': 'nz',
  // UEFA (16)
  'austria': 'at', 'ออสเตรีย': 'at',
  'belgium': 'be', 'เบลเยียม': 'be',
  'bosnia and herzegovina': 'ba', 'บอสเนียและเฮอร์เซโกวีนา': 'ba',
  'croatia': 'hr', 'โครเอเชีย': 'hr',
  'czechia': 'cz', 'czech republic': 'cz', 'สาธารณรัฐเช็ก': 'cz',
  'england': 'gb-eng', 'อังกฤษ': 'gb-eng',
  'france': 'fr', 'ฝรั่งเศส': 'fr',
  'germany': 'de', 'เยอรมนี': 'de',
  'netherlands': 'nl', 'holland': 'nl', 'เนเธอร์แลนด์': 'nl',
  'norway': 'no', 'นอร์เวย์': 'no',
  'portugal': 'pt', 'โปรตุเกส': 'pt',
  'scotland': 'gb-sct', 'สกอตแลนด์': 'gb-sct',
  'spain': 'es', 'สเปน': 'es',
  'sweden': 'se', 'สวีเดน': 'se',
  'switzerland': 'ch', 'สวิตเซอร์แลนด์': 'ch',
  'turkey': 'tr', 'türkiye': 'tr', 'ตุรกี': 'tr',
}

export function getFlagCode(teamName: string): string {
  return FLAGS[teamName.toLowerCase().trim()] ?? ''
}

export const TEAMS: { name: string; code: string }[] = [
  // AFC
  { name: 'Australia', code: 'au' },
  { name: 'Iran', code: 'ir' },
  { name: 'Iraq', code: 'iq' },
  { name: 'Japan', code: 'jp' },
  { name: 'Jordan', code: 'jo' },
  { name: 'Korea Republic', code: 'kr' },
  { name: 'Qatar', code: 'qa' },
  { name: 'Saudi Arabia', code: 'sa' },
  { name: 'Uzbekistan', code: 'uz' },
  // CAF
  { name: 'Algeria', code: 'dz' },
  { name: 'Cape Verde', code: 'cv' },
  { name: 'Côte d\'Ivoire', code: 'ci' },
  { name: 'DR Congo', code: 'cd' },
  { name: 'Egypt', code: 'eg' },
  { name: 'Ghana', code: 'gh' },
  { name: 'Morocco', code: 'ma' },
  { name: 'Senegal', code: 'sn' },
  { name: 'South Africa', code: 'za' },
  { name: 'Tunisia', code: 'tn' },
  // CONCACAF
  { name: 'Canada', code: 'ca' },
  { name: 'Curaçao', code: 'cw' },
  { name: 'Haiti', code: 'ht' },
  { name: 'Mexico', code: 'mx' },
  { name: 'Panama', code: 'pa' },
  { name: 'USA', code: 'us' },
  // CONMEBOL
  { name: 'Argentina', code: 'ar' },
  { name: 'Brazil', code: 'br' },
  { name: 'Colombia', code: 'co' },
  { name: 'Ecuador', code: 'ec' },
  { name: 'Paraguay', code: 'py' },
  { name: 'Uruguay', code: 'uy' },
  // OFC
  { name: 'New Zealand', code: 'nz' },
  // UEFA
  { name: 'Austria', code: 'at' },
  { name: 'Belgium', code: 'be' },
  { name: 'Bosnia and Herzegovina', code: 'ba' },
  { name: 'Croatia', code: 'hr' },
  { name: 'Czechia', code: 'cz' },
  { name: 'England', code: 'gb-eng' },
  { name: 'France', code: 'fr' },
  { name: 'Germany', code: 'de' },
  { name: 'Netherlands', code: 'nl' },
  { name: 'Norway', code: 'no' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Scotland', code: 'gb-sct' },
  { name: 'Spain', code: 'es' },
  { name: 'Sweden', code: 'se' },
  { name: 'Switzerland', code: 'ch' },
  { name: 'Türkiye', code: 'tr' },
].sort((a, b) => a.name.localeCompare(b.name))
